title: My Journey Through Github Hell
author: Wob
email: my-email@a-domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm writing a description here as I've been asked to do.
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
